import type { Note } from "@/lib/types"

// --- Shared mock notes for demo mode ---------------------------------------
export const demoNotes: Note[] = [
  {
    id: "demo-1",
    title: "Welcome to EzNote Social! 🎉",
    content:
      "<p>This is your social timeline! Share your thoughts, memories, and experiences with the community.</p><p>✨ <strong>Features:</strong></p><ul><li>📱 Share notes with images</li><li>🌍 Public timeline like social media</li><li>🔒 Private room for personal notes</li><li>💎 Permanent memories on blockchain</li></ul>",
    images: ["/placeholder.svg?height=300&width=500"],
    visibility: "public",
    tags: ["welcome", "social", "features"],
    authorId: "demo-user-123",
    authorName: "Demo User",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
    likes: 12,
  },
  {
    id: "demo-2",
    title: "Beautiful sunset today! 🌅",
    content: "<p>Caught this amazing sunset on my evening walk. Nature never fails to amaze me! 🧡</p>",
    images: ["/placeholder.svg?height=400&width=600"],
    visibility: "public",
    tags: ["sunset", "nature", "photography"],
    authorId: "demo-user-456",
    authorName: "Nature Lover",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    likes: 24,
  },
  {
    id: "demo-3",
    title: "My Permanent Memory 💎",
    content: "<p>Graduated today! This moment will be stored forever on the blockchain as a permanent memory. 🎓✨</p>",
    images: ["/placeholder.svg?height=400&width=600"],
    visibility: "permanent",
    tags: ["graduation", "milestone", "achievement"],
    authorId: "demo-user-789",
    authorName: "Graduate",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    isPermanent: true,
    blockchainHash: "0x1234567890abcdef...",
    likes: 45,
  },
  {
    id: "demo-4",
    title: "Coffee and coding ☕",
    content: "<p>Perfect morning setup! Working on some exciting new features. #DevLife</p>",
    images: ["/placeholder.svg?height=300&width=500"],
    visibility: "public",
    tags: ["coding", "coffee", "work"],
    authorId: "demo-user-101",
    authorName: "Developer",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
    likes: 18,
  },
  {
    id: "demo-5",
    title: "Weekend hiking adventure! 🥾",
    content:
      "<p>Explored a new trail today with amazing views! The fresh air and exercise were exactly what I needed.</p>",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    visibility: "public",
    tags: ["hiking", "adventure", "weekend", "nature"],
    authorId: "demo-user-202",
    authorName: "Adventure Seeker",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    likes: 31,
  },
]

export const demoPrivateNotes: Note[] = [
  {
    id: "private-1",
    title: "Personal Reflection",
    content:
      "<p>Today was challenging but I learned a lot about myself. Sometimes the hardest days teach us the most valuable lessons.</p>",
    visibility: "private",
    tags: ["reflection", "personal", "growth"],
    authorId: "demo-user-123",
    authorName: "Demo User",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
  },
  {
    id: "private-2",
    title: "Goals for Next Month",
    content:
      "<p>Private goals I want to achieve:</p><ul><li>Read 2 books</li><li>Exercise 4 times a week</li><li>Learn a new skill</li><li>Spend more time with family</li></ul>",
    visibility: "private",
    tags: ["goals", "planning", "personal"],
    authorId: "demo-user-123",
    authorName: "Demo User",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
  },
  {
    id: "private-3",
    title: "Secret Recipe 👨‍🍳",
    content:
      "<p>My grandmother's secret pasta sauce recipe that I don't want to share publicly yet:</p><p><strong>Ingredients:</strong> tomatoes, garlic, basil, secret spice blend...</p>",
    images: ["/placeholder.svg?height=300&width=500"],
    visibility: "private",
    tags: ["recipe", "family", "cooking"],
    authorId: "demo-user-123",
    authorName: "Demo User",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 16),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 16),
  },
]
